/**
 * TEMPLATE: visual-test.swift
 * PURPOSE: XCUITest visual check — generated by ios-pilot Phase 3.6
 * GENERATED FOR: {feature_slug}
 *
 * HOW TO USE:
 * 1. AI substitutes all {placeholders} from 01-spec.md ## Visual Anchors
 * 2. Place in: {AppName}UITests/ target
 * 3. Run: xcodebuild test -scheme {AppScheme} -only-testing:{AppName}UITests/{FeatureSlug}VisualTests
 *
 * REQUIREMENTS:
 * - UITests target in project (Xcode → File → New → Target → UI Testing Bundle)
 * - Screenshots stored in: app Documents/ios_pilot_screenshots/
 */

import XCTest

/**
 * Visual check for {feature_slug}.
 * Auto-generated by ios-pilot from ## Visual Anchors in 01-spec.md.
 *
 * Screens verified: {comma-separated screen names}
 * ADVISORY: Failures in this suite are warnings, not pipeline blockers.
 */
// swiftlint:disable all
// NOTE: {FeatureSlug} is a template placeholder — replace with PascalCase feature name
// e.g. {FeatureSlug} = "Login" → LoginVisualTests
final class FeatureSlugVisualTests: XCTestCase { // rename to {FeatureSlug}VisualTests

    var app: XCUIApplication!

    var screenshotDir: URL {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
        return docs.appendingPathComponent("wira_screenshots")
    }

    override func setUpWithError() throws {
        continueAfterFailure = false
        app = XCUIApplication()
        app.launchArguments = ["--uitesting"]
        app.launch()
        try? FileManager.default.createDirectory(at: screenshotDir, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        app = nil
    }

    // ─── VISUAL SCREEN CHECKS ──────────────────────────────────────────────
    //
    // Per visual_anchor in 01-spec.md, generate one test method below.
    // Naming: test_visual_{ScreenName}
    //
    // Template for each screen:
    //
    // /**
    //  * Visual check: {ScreenName}
    //  * Spec: {description}
    //  * Key elements: {key_elements}
    //  */
    // func test_visual_{ScreenName}() throws {
    //     // Navigate to screen if needed
    //     // e.g., app.buttons["nav_{screen_name}"].tap()
    //
    //     // Wait for screen root element
    //     let screen = app.otherElements["{screen_accessibility_id}"]
    //     XCTAssertTrue(screen.waitForExistence(timeout: 5), "{ScreenName} should be visible")
    //
    //     // Assert key elements
    //     XCTAssertTrue(app.{elementType}["{element_id}"].exists, "{element} should be visible")
    //
    //     // Negative checks (elements that must NOT be present)
    //     // XCTAssertFalse(app.activityIndicators.firstMatch.exists, "Spinner should be hidden")
    //
    //     captureScreenshot(name: "{ScreenName}")
    // }

    // TODO: Replace with generated test methods for each Visual Anchor

    // ─── HELPER ────────────────────────────────────────────────────────────

    /**
     * Saves screenshot to Documents for simctl pull + attaches to XCResult for CI.
     */
    private func captureScreenshot(name: String) {
        let screenshot = XCUIScreen.main.screenshot()

        // Attach to XCResult (reliable in CI)
        let attachment = XCTAttachment(screenshot: screenshot)
        attachment.name = name
        attachment.lifetime = .keepAlways
        add(attachment)

        // Save to file for simctl pull (reliable in local dev)
        let fileURL = screenshotDir.appendingPathComponent("\(name).png")
        do {
            try screenshot.pngRepresentation.write(to: fileURL)
        } catch {
            // Non-fatal — XCTAttachment above still captures it
        }
    }
}
